# Generated by Django 2.0.7 on 2018-07-27 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participate',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participate',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Paper'),
        ),
        migrations.AddField(
            model_name='answer',
            name='participate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Participate'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='select',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.Choice'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='answer',
            order_with_respect_to='participate',
        ),
    ]
