# Generated by Django 2.0.7 on 2018-07-28 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_preview_image'),
        ('answers', '0002_auto_20180727_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='select',
        ),
        migrations.AddField(
            model_name='select',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Answer'),
        ),
        migrations.AddField(
            model_name='select',
            name='option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.Choice'),
        ),
    ]
