# Generated by Django 2.0.7 on 2018-07-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20180728_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='select',
            old_name='option',
            new_name='choice',
        ),
    ]
