# Generated by Django 2.0.7 on 2018-08-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_auto_20180801_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participate',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participates', to='papers.Paper'),
        ),
    ]
