# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-09 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperuser',
            name='sid',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
