# Generated by Django 2.0.7 on 2018-09-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_paperuser_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperuser',
            name='is_kaistian',
            field=models.BooleanField(default=False),
        ),
    ]
