# Generated by Django 2.0.7 on 2018-07-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default='option', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Title', max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(default=None)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_validated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='empty question', max_length=140)),
                ('type', models.CharField(choices=[('C', 'Checkbox'), ('R', 'Radio'), ('O', 'Open-Ended')], max_length=1)),
                ('is_multiple', models.BooleanField(default=False)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Paper')),
            ],
        ),
    ]
