# Generated by Django 2.0.7 on 2018-07-27 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Question'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='question',
            order_with_respect_to='paper',
        ),
        migrations.AlterOrderWithRespectTo(
            name='choice',
            order_with_respect_to='question',
        ),
    ]
