# Generated by Django 2.0.7 on 2018-07-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20180727_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='preview_image',
            field=models.FileField(default=None, upload_to='previews/'),
        ),
    ]
