# Generated by Django 2.0.7 on 2018-07-31 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='papers.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='papers.Paper'),
        ),
    ]
