# Generated by Django 2.0.7 on 2018-08-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20180801_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='poster_url',
            field=models.URLField(null=True),
        ),
    ]
