# Generated by Django 2.0.7 on 2018-09-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_paper_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='only_kaist',
            field=models.BooleanField(default=False),
        ),
    ]
